- name: ensure git and sqlite are installed
  become: yes
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - git
    - sqlite
    - mysql-devel

- name: generating secrets
  become_user: vagrant
  shell: bundle exec rake {{item}}
  args:
    chdir: /vagrant
  with_items:
    - circa:generate_secrets
    - db:schema:load
    - db:seed
    - users:create_admin


# - name: load schema
#   become_user: vagrant
#   shell: bundle exec rake db:schema:load
#   args:
#     chdir: /vagrant
# - name: seed db
#   become_user: vagrant
#   shell: bundle exec rake db:seed
#   args:
#     chdir: /vagrant
# - name: create admin user
#   become_user: vagrant
#   shell: bundle exec rake users:create_admin
#   :
#   args:
#     chdir: /vagrant
