- name: ensure git and sqlite are installed
  become: yes
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - git
    - sqlite
    - mysql-devel

- name: generating secrets
  become_user: vagrant
  shell: bash -lc "bundle exec rake circa:generate_secrets"
  args:
    chdir: /vagrant

# - name: run rake scripts
#   command: "{{bundler_executable_path}} exec rake {{item}}"
#   with_items:
#     - db:schema:load
#     - db:seed
#     - users:create_admin
