---
galaxy_info:
  author: RVM
  description: The official RVM role to install and manage your ruby versions
  license: MIT
  min_ansible_version: 2.4

  platforms:
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

  galaxy_tags:
    - development
    - ruby

dependencies: []
