- name: Ensure unzip is installed
  become: yes
  yum:
    name: "{{item}}"
    state: latest
  with_items:
    - unzip
    - git

#https://github.com/archivesspace/archivesspace/releases/download/v2.1.2/archivesspace-v2.1.2.zip
- name: Ensure Archives Space directory exists
  file:
    path: "{{ansible_env.HOME}}/archivesspace"
    state: directory

- name: Download and unzip Archives Space
  unarchive:
    src: https://github.com/archivesspace/archivesspace/releases/download/v2.1.2/archivesspace-v2.1.2.zip
    dest: "{{ansible_env.HOME}}"
    mode: 0700
    remote_src: yes
    creates: "{{ansible_env.HOME}}/archivesspace/archivesspace.sh"

- name: Download archivesspace plugins
  git:
    repo: "{{item.src}}"
    dest: "{{ansible_env.HOME}}/archivesspace/plugins/{{item.name}}"
    accept_hostkey: true
  with_items:
    - name: display_uri
      src: https://github.com/NCSU-Libraries/archivesspace_display_uri_plugin.git
    - name: delete_button_context
      src: https://github.com/NCSU-Libraries/archivesspace_delete_button_context_plugin.git

- name: Enable plugins
  lineinfile:
    path: "{{ansible_env.HOME}}/archivesspace/config/config.rb"
    insertafter: "^#AppConfig[:plugins]"
    line: "AppConfig[:plugins] = ['display_uri', 'delete_button_context']"

- name: Ensure Archives Space is not already running
  command: "./archivesspace.sh stop"
  args:
    chdir: "{{ansible_env.HOME}}/archivesspace"

- name: Start ArchivesSpace
  command: "./archivesspace.sh start"
  args:
    chdir: "{{ansible_env.HOME}}/archivesspace"

- name: Waiting for ArchivesSpace to start
  wait_for:
    host: "localhost"
    port: 8081
    state: started
