defaults: &defaults
  archivesspace_backend_port: '8089'
  archivesspace_frontend_port: '8080'
  archivesspace_solr_port: '8090'
  archivesspace_solr_core_path: '/collection1/'
  archivesspace_username: admin
  archivesspace_password: admin
  archivesspace_host: localhost

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults
  archivesspace_host: staging.archivesspace.yourorg.org

production:
  <<: *defaults
  archivesspace_host: archivesspace.yourorg.org
