defaults: &defaults
  order_notification_default_email: 'you@yourorg.org'
  order_notification_digital_items_email: 'you@yourorg.org'
  circa_email: 'circa@yourorg.org'
  circa_email_display_name: 'Circa'

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
