defaults: &defaults
  solr_host: localhost
  solr_port: '8983'
  solr_core_name: 'circa'
  solr_core_path: /solr/circa/

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
